Repository AY2425S1-CS2103T-F08-2/tp, pull requests merged in 2024-10, with the labels that each got.

#38 Update set-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task

#37 Developer guide: update non-functional requirements
  docs/DeveloperGuide.md
Labels: type.Task

#36 DG: update use cases
  docs/DeveloperGuide.md
Labels: type.Task

#39 DG: Update target user profile, value proposition, user stories, glos…
  docs/DeveloperGuide.md
Labels: type.Task

#48 Mvp rename app UI
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#49 Branch update person model
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task

#52 Exit command: display exit message
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task

#57 MVP - Remove fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Detail.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#62 MVP - Gender field
  src/main/java/seedu/address/model/person/Gender.java
  src/test/java/seedu/address/model/person/GenderTest.java
Labels: type.Task

#67 Update Age class to check age constraints and tests for invalid age
  src/main/java/seedu/address/model/person/Age.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task

#66 Update save error messages
  src/main/java/seedu/address/logic/LogicManager.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Task

#71 Standardise message and class names missed during v1.2
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/StudyGroupTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/StudyGroupTagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, type.Bug

#68 Add Ui message for load failure and also add new test for saving
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonAddressBookStorageTest/writeAccessDeniedAddressBook.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Task

#73 MVP - Fix UI bugs
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#77 Alpha Version - Bulk Deletion Feature
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#79 Alpha Version - StudyGroupTag refactoring
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/StudyGroupTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudyGroupTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/writeAccessDeniedAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/StudyGroupTagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#89 Update ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#83 Enable assertions
  build.gradle
Labels: type.Task

#90 Update UML diagram for ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#91 Update BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task

#93 Alpha Version - Add find command sequence diagram
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: type.Task

#80 Alpha Version - Edit feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#95 Alpha version - Update UML diagrams (ModelClassDiagram, BetterModelClassDiagram, StorageClassDiagram)
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task

#98 Fix save feature bugs
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Task

#100 Alpha version - Message standardization (edit feature)
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug

#102 Alpha version - Code standardization (miscellaneous)
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Bug

#106 Alpha version - Add export feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/ExportCommandTest/expectedExportFilteredList.txt
  src/test/data/ExportCommandTest/expectedExportUnfilteredList.txt
  src/test/data/ExportCommandTest/validExportFile.txt
  src/test/data/ExportCommandTest/validExportFile2.txt
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: type.Task

#112 Fix delete parse message
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#107 Alpha version - Edit: remove tags
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Gender.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Task

#111 PUML - Multiplicity in ModelClassDiagram is rendered with unfavourable placement
  docs/images/ModelClassDiagram.png
Labels: type.Bug

#119 Add clear command for filtered list functionality
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/data/ExportCommandTest/expectedExportFilteredList.txt
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Task

#123 Alpha Version - Handle range for find and delete command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#127 StudyGroupTag - Expand constraint on study group names
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/tag/StudyGroupTag.java
Labels: type.Bug, priority.Medium

#135 Alpha version - ReadMe
  README.md
Labels: type.Alpha-Bug, priority.High

#137 Alpha version - index.md
  docs/index.md
Labels: type.Alpha-Bug, priority.High

#129 Alpha version - Help feature
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#133 Alpha version - About Us
  docs/AboutUs.md
  docs/team/jiawei.md
  docs/team/kayhian.md
  docs/team/kexin.md
  docs/team/prisha.md
  docs/team/sanchita.md
Labels: type.Task

#154 Add check to prevent duplicate input fields
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Alpha-Bug, severity.Medium

#156 Add validation check for find command input
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicateTest.java
Labels: type.Alpha-Bug, severity.High

#110 DG - Add find command implementation details
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram-Logic.puml
  docs/diagrams/FindSequenceDiagram-PredicateModel.puml
  docs/diagrams/PredicateGroupSequenceDiagram.puml
  docs/images/FindSequenceDiagram-Logic.png
  docs/images/FindSequenceDiagram-PredicateModel.png
  docs/images/PredicateGroupSequenceDiagram.png
Labels: type.Task

#125 Alpha Version - Assign study groups randomly
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignStudyGroupTagDescriptorTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/testutil/AssignStudyGroupTagDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#150 Fix StudyGroupTag equals function
  src/main/java/seedu/address/model/tag/StudyGroupTag.java
  src/test/java/seedu/address/model/tag/StudyGroupTagTest.java
Labels: type.Alpha-Bug, priority.High, severity.Medium

#159 Add warning messages to edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Alpha-Bug, severity.Low

#158 Implement invalid input handling for Find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/DetailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/StudyGroupsContainKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/DetailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PredicateGroupTest.java
  src/test/java/seedu/address/model/person/predicates/StudyGroupsContainKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/FindUtil.java
Labels: type.Alpha-Bug, priority.High, severity.High

#161 Update add and delete commands in UG
  docs/UserGuide.md
Labels: type.Task

#167 Alpha version - Update DG (Implementation, Use Cases)
  docs/DeveloperGuide.md
Labels: type.Task

#163 Alpha version - Email standardization (Test)
  src/test/data/ExportCommandTest/expectedExportFilteredList.txt
  src/test/data/ExportCommandTest/expectedExportUnfilteredList.txt
  src/test/data/ExportCommandTest/validExportFile.txt
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Alpha-Bug

#165 Alpha Version - Add test case for StudyGroupTag
  src/test/java/seedu/address/model/tag/StudyGroupTagTest.java
Labels: type.Task

#170 Add list sorting and refactor UniquePersonList to UniqueSortedPersonList
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniqueSortedPersonList.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/UniqueSortedPersonListTest.java
Labels: type.Task

#148 Update features section in UG
  docs/UserGuide.md
  docs/images/assignMaleGroupResult.png
  docs/images/assignP90Result.png
  docs/images/findMultipleCriteria.png
Labels: type.Task

#169 Alpha Version - Update index.md with new UI
  docs/images/Ui.png
Labels: type.Task

#139 Alpha version - User Guide (Quick Start)
  docs/UserGuide.md
  docs/images/check_java_version.png
  docs/images/type_command.png
Labels: type.Task

#179 Alpha version - Make email equals method case insensitive
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.Low, alpha-bug

#177 Alpha Version - Clicking Person card unwanted appearence
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, severity.VeryLow, alpha-bug

#186 Alpha Version - Punctuation inconsistencies: UI 2
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#188 Alpha Version - Punctuation inconsistencies: UI 1
  src/main/java/seedu/address/ui/UiManager.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#189 Alpha Version - Punctuation inconsistencies: Logic
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Bug, severity.VeryLow, alpha-bug
