Repository AY2425S1-CS2103T-F08-2/tp, pull requests merged in 2024-11, with the labels that each got.

#192 Alpha version - Fix duplicate export file handling
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/ExportCommandTest/validExportFile.txt
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: type.Bug, severity.Low, alpha-bug

#196 Update UG list, clear, export
  docs/UserGuide.md
Labels: type.Task

#202 Update DG user stories
  docs/DeveloperGuide.md
Labels: type.Task

#200 Alpha version - Update UG edit, save, help
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task

#198 Update DG effort
  docs/DeveloperGuide.md
Labels: type.Task

#204 Alpha version - Update DG fix alignment
  docs/DeveloperGuide.md
Labels: type.Bug

#205 Modify export command example
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Task, alpha-bug

#206 Alpha version - Edit command error message
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/data/ExportCommandTest/validExportFile.txt
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Task, alpha-bug

#207 Modify delete error message to include range
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Task, alpha-bug

#187 Fix references to find command format
  docs/UserGuide.md
Labels: type.Bug

#182 Change StudyGroupTag equals function
  src/main/java/seedu/address/model/tag/StudyGroupTag.java
Labels: type.Bug

#210 Alpha version - DG (Instructions for Manual Testing)
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#214 Fix long message usage
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Bug, severity.VeryLow

#126 Alpha version - Add confirm command to confirm clearing
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ConfirmClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#215 Alpha version - Follow up on User Guide (Quick Start)
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui_annotated.png
Labels: type.Task

#212 Update UG with new description
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kayhian.md
Labels: type.Bug

#218 Update features in README
  README.md
Labels: type.Bug

#222 Add message for no participants to clear
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug, severity.Medium

#220 Update acknowledgements, use cases and testing in DG
  docs/DeveloperGuide.md
Labels: type.Bug

#226 Fix bug in Use Case
  docs/DeveloperGuide.md
Labels: type.Bug, alpha-bug

#227 Alpha Version - Command Box too Short
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#228 Update version number and my contributions page
  docs/team/prisha.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#231 Revert "Alpha Version - Command Box too Short"
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#235 Fix bug in UG
  docs/UserGuide.md
Labels: type.Bug, alpha-bug

#237 Add page break to DG for formatting
  docs/DeveloperGuide.md
Labels: type.Task

#307 Fix unhandled duplicate keyword in find command
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.Medium, type.FunctionalityBug

#309 Fix text wrapping issue
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#312 Revert "Fix text wrapping issue"
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#310 Update incorrect constaint on age integer field
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/AgeTest.java
  src/test/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicateTest.java
Labels: type.FunctionalityBug

#316 Code standardization - Fix coding standard violation (naming)
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#318 ReadMe: Remove repeated content
  README.md
Labels: type.Task

#311 Fix find command reversed range wrong output
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
Labels: type.FunctionalityBug

#314 DG: Fix bugs
  docs/DeveloperGuide.md
Labels: severity.Low, type.DocumentationBug

#313 UG: Fix bugs
  docs/UserGuide.md
  docs/images/valid_JSON_file.png
  src/main/java/seedu/address/model/person/Age.java
Labels: severity.Low, type.DocumentationBug

#321 Fix delete and add error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug

#323 Add known issues and planned enhancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#325 Widen message for confirm clearing
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: type.Bug

#327 Refine Javadoc comments
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/util/ConfigUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Detail.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueSortedPersonList.java
  src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
Labels: type.Task

#320 AboutUs: Update files to match project
  docs/AboutUs.md
  docs/team/jiawei.md
  docs/team/k-hian.md
  docs/team/prishavp.md
  docs/team/sannie-beep.md
  docs/team/wkxcass.md
  docs/team/wujiaweijoanna.md
Labels: type.Task

#330 Refine Javadoc Comments (Storage Component)
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
Labels: type.Task

#335 Update md doc
  docs/team/wujiaweijoanna.md
Labels: type.Task

#333 Justify duplicate emails, specify proper email format, add links
  docs/UserGuide.md
Labels: severity.Low, response.Accepted, type.DocumentationBug

#337 Refine UG export command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
Labels: type.Bug

#341 Fix assign command warning format
  docs/UserGuide.md
Labels: type.DocumentationBug
